/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import Controlador.ControladorUnirse;
import Logica.Fachada;
import dominio.Jugador;
import Vista.IVistaUnirse;
import dominio.Mesa;
import java.util.ArrayList;

/**
 *
 * @author Usuario
 */
public class DialogoUnirse extends javax.swing.JDialog implements IVistaUnirse {
    
       protected final ControladorUnirse controlador;
       protected final Jugador jugador;
       protected final Fachada fachada;
       protected int mesaSeleccionada;

    /**
     * Creates new form DialogoListarMesas
     */
    public DialogoUnirse(java.awt.Frame parent, boolean modal,Fachada fachada, Jugador jugador) {
        super(parent, modal);
        this.controlador=new ControladorUnirse(fachada,this);
        this.jugador=jugador;
        this.fachada = fachada;
        this.mesaSeleccionada = 0;
        initComponents();
        this.cargarMesasActivas(fachada.getMesasActivas());
        this.setTitle(String.format("Mesas abiertas, Usuario logueado: %s", jugador.getNombreCompleto()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        join = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        mesasActivas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        join.setText("Ingresar");
        join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        mesasActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesasActivasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mesasActivas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(join, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(mesasActivas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(join)
                    .addComponent(logout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void joinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinActionPerformed
        this.controlador.unirse(1, this.jugador);
    }//GEN-LAST:event_joinActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        this.controlador.logout();
    }//GEN-LAST:event_logoutActionPerformed

    private void mesasActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesasActivasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesasActivasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton join;
    private javax.swing.JButton logout;
    private javax.swing.JComboBox<String> mesasActivas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarMesasActivas(ArrayList<Mesa> mesasActivas) {
        for (Mesa mesa: mesasActivas) {
            this.mesasActivas.addItem("Mesa " + String.valueOf(mesa.getId()));
        }
    }
}
