package ui;

import Common.DisplayerStrategy;
import Common.IDisplayerStrategy;
import componentes.PanelInfoJugador;
import controladores.ControladorVistaMesaJugador;
import vistas.IVistaMesaJugador;
import componentes.PanelRuleta;
import dominio.EnumTipoApuesta;
import dominio.modelosVista.ModeloMesaJugador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author digregor
 */
public class DialogoVentanaMesaJugador extends javax.swing.JFrame implements IVistaMesaJugador, PanelInfoJugador.Escuchador {

    private final ControladorVistaMesaJugador controlador;
    private final Selector selector;
    private Integer ficha;
    private ModeloMesaJugador modelo;
    private final IDisplayerStrategy displayer = new DisplayerStrategy ();

    /**
     * Creates new form NewJFrame
     */
    public DialogoVentanaMesaJugador(ModeloMesaJugador modelo) {
        initComponents();
        this.selector = new Selector ();
        this.ficha = 1;
        this.modelo = modelo;
        this.controlador = new ControladorVistaMesaJugador (this,modelo);
        this.setup();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        r = new componentes.PanelRuleta();
        panelEstadisticasJugador = new componentes.PanelJugador();
        panelInfoJugador1 = new componentes.PanelInfoJugador();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Apostar al 0");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panelEstadisticasJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelInfoJugador1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(r, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelInfoJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEstadisticasJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int n = selector.universalCellCode;
        int monto = panelInfoJugador1.getModelo().getTotal();
        String idJugador = modelo.getIdJugador();
        r.setApuesta(n, monto);
        controlador.apostar (n, monto, modelo.getMesa(), idJugador);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private componentes.PanelJugador panelEstadisticasJugador;
    private componentes.PanelInfoJugador panelInfoJugador1;
    private componentes.PanelRuleta r;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarTiposDeApuesta(ArrayList<EnumTipoApuesta> tiposDeApuesta) {
        for (EnumTipoApuesta enumApuesta : tiposDeApuesta) {
            switch (enumApuesta) {
                case Colores:
                    displayer.mostrarColor(r);
                    break;
                case Docenas:
                    displayer.mostrarDocenas(r);
                    break;

            }
        }
    }
    
    private void setup () {
        r.agregar(selector);
        this.panelEstadisticasJugador.setModelo(modelo);
        this.panelEstadisticasJugador.setVista(this);
        this.panelInfoJugador1.setModelo(modelo);
        this.panelInfoJugador1.addEventListener(this);
        this.displayer.ocultarTodo(r);
        this.controlador.mostrarTiposDeApuesta (modelo.getMesa());
        this.panelInfoJugador1.actualizar();
    }

    @Override
    public void refrescar() {
        this.modelo = controlador.refrescarModelo (modelo);
        this.panelInfoJugador1.setModelo(modelo);
        this.panelInfoJugador1.actualizar();
    }

    @Override
    public void mostrarDialogoDeError(String message) {
        JOptionPane.showMessageDialog(this, message, "Hubo un problema...", JOptionPane.ERROR_MESSAGE);

    }

    @Override
    public void fichaSeleccionada(int ficha) {
        this.ficha = ficha;
    }

    private class Selector implements PanelRuleta.Escuchador {
        
        int universalCellCode = 0;
        
        @Override
        public void celdaSeleccionada(int universalCellCode) {
            this.universalCellCode = universalCellCode;
            String labelApuesta = "Apostar al " + String.valueOf(universalCellCode);
            jButton2.setText(labelApuesta);
        }
        
    }
    
    public void abandonar (){
        this.dispose();
    }

}
