package ui;

 
import componentes.PanelRuleta;
import controladores.ControladorVistaMesaCrupier;
import dominio.EnumTipoApuesta;
import dominio.Mesa;
import dominio.modelosVista.ModeloInfoCrupier;
import java.util.ArrayList;
import vistas.IVistaMesaCrupier;
 

/**
 *
 * @author digregor
 */
public class DialogoVentanaMesaCrupier extends javax.swing.JFrame implements IVistaMesaCrupier {

    int apuestaRojo = 0;
    protected final ControladorVistaMesaCrupier controlador;
    protected final Mesa m;

    /**
     * Creates new form NewJFrame
     */
    public DialogoVentanaMesaCrupier(Mesa m) {
        initComponents();
        ocultarDocenas();
        ocultarColor();
        ocultarParidad();
        this.m = m;
        this.controlador = new ControladorVistaMesaCrupier(m, this);
        ocultarColor();
        controlador.mostrarTiposApuestaSeleccionados(m);
        controlador.cargarNumeroDeMesaEnPanel(m);
        controlador.cargarTotalApostadoEnPanel(m);
        controlador.cargarNumeroDeRondaEnPanel(m);
        controlador.cargarNumeroDeApuestasEnPanel(m);
        
        this.panelInfoCrupier1.setNumeroMesa(m.getId());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        r = new componentes.PanelRuleta();
        panelInfoCrupier1 = new componentes.PanelInfoCrupier();
        panelTableroRuleta1 = new componentes.PanelTableroRuleta();
        jLabel1 = new javax.swing.JLabel();
        lbl_ultimosLanzamientos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ultimos Lanzamientos:");

        lbl_ultimosLanzamientos.setText("N/A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTableroRuleta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_ultimosLanzamientos))
                            .addComponent(panelInfoCrupier1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 70, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelInfoCrupier1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_ultimosLanzamientos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTableroRuleta1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void mostrarColor() {                                         
        r.setVisible(PanelRuleta.ROJO, true);
        r.setVisible(PanelRuleta.NEGRO, true);
    }                                        
    private void ocultarColor() {                                         
        r.setVisible(PanelRuleta.ROJO, false);
        r.setVisible(PanelRuleta.NEGRO, false);
    }                                        
    private void mostrarDocenas() {                                         
        r.setVisible(PanelRuleta.PRIMERA_DOCENA, true);
        r.setVisible(PanelRuleta.SEGUNDA_DOCENA, true);
        r.setVisible(PanelRuleta.TERCERA_DOCENA, true);

    }                                        
    private void ocultarDocenas() {                                         
        r.setVisible(PanelRuleta.PRIMERA_DOCENA, false);
        r.setVisible(PanelRuleta.SEGUNDA_DOCENA, false);
        r.setVisible(PanelRuleta.TERCERA_DOCENA, false);

    }        
    
    private void mostrarParidad(){
        r.setVisible(PanelRuleta.PAR,true);
        r.setVisible(PanelRuleta.IMPAR,true);
    }
     private void ocultarParidad(){
        r.setVisible(PanelRuleta.PAR,false);
        r.setVisible(PanelRuleta.IMPAR,false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_ultimosLanzamientos;
    private componentes.PanelInfoCrupier panelInfoCrupier1;
    private componentes.PanelTableroRuleta panelTableroRuleta1;
    private componentes.PanelRuleta r;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarTiposApuestaSeleccionados(ArrayList<EnumTipoApuesta> listarTiposApuestaSeleccionados) {
        for (EnumTipoApuesta enumApuesta : listarTiposApuestaSeleccionados) {
            switch (enumApuesta) {
                case Paridad: 
                    mostrarParidad();
                    break;
                case Colores:
                    mostrarColor();
                    break;
                case Docenas:
                    mostrarDocenas();
                    break;

            }
        }
    }

    @Override
    public void cargarNumeroDeMesaEnPanel(int id) {
        this.panelInfoCrupier1.setNumeroMesa(id);
        }

    @Override
    public void cargarTotalApostadoEnPanel(Mesa m) {
         this.panelInfoCrupier1.setTotalApostado(m.getBalance());
     }

    @Override
    public void cargarNumeroDeRondaEnPanel(int id) {
       this.panelInfoCrupier1.setNumeroRonda(id);
    }

    @Override
    public void cargarNumeroDeApuestasEnPanel(int cantidadApuestas) {
        this.panelInfoCrupier1.setCantidadApuestas(cantidadApuestas);
     }

    @Override
    public void cargarListaJugadores(ArrayList<ModeloInfoCrupier> jugadoresSaldo) {
        this.panelTableroRuleta1.setJugadoresSaldo(jugadoresSaldo);

    }
}
