/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import Controlador.ControladorCrearMesa;
import Logica.FachadaServicios;
import Vista.IVistaCrearMesa;
import dominio.Crupier;
import dominio.Usuario;

/**
 *
 * @author Usuario
 */
public class DialogoCrearMesa extends javax.swing.JDialog implements IVistaCrearMesa{

         protected final ControladorCrearMesa controlador;
         protected final Crupier c;
    /**
     * Creates new form DialogoCrearMesa
     */
    public DialogoCrearMesa(java.awt.Frame parent, boolean modal,FachadaServicios f, Crupier crupier) {
        super(parent, modal);
        this.controlador=new ControladorCrearMesa(f,this);
        initComponents();
        this.c=crupier;
        this.setTitle(String.format("Crear Mesa, Crupier logueado: %s", c.getNombreCompleto()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
