/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package componentes;

import javax.swing.JLabel;
import javax.swing.JSeparator;

/**
 *
 * @author nacho
 */
public class PanelInfoCrupier extends javax.swing.JPanel {

    /**
     * Creates new form PanelInfoJugador
     */
    public PanelInfoCrupier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void setSaldoInicial(float saldoInicial) {
        this.lbl_totalApostado.setText(String.valueOf(saldoInicial));
    }

    public void setNumeroMesa(int mesa) {
        this.ruleta.setText("Ruleta #" + String.valueOf(mesa));
    }

    public void setNumeroRonda(int ronda) {
        this.ronda.setText("Ronda #" + String.valueOf(ronda));
    }

    public void setTotalApostado(float totalApostado) {
        this.lbl_totalApostado.setText(String.valueOf(totalApostado));

    }

    public void setCantidadApuestas(int cantidadApuestas) {
        this.jLbl_cantidadApuestas_Valor.setText(String.valueOf(cantidadApuestas));

    }
    
    // Cargar listas de efectos


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ruleta = new javax.swing.JLabel();
        ronda = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        numeroSorteado = new javax.swing.JLabel();
        lbl_totalApostado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLbl_Apuestas_titulo = new javax.swing.JLabel();
        jLbl_cantidadApuestas_Valor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        javax.swing.JButton jBtn_LanzarPagar = new javax.swing.JButton();
        jBtn_CerrarMesa = new javax.swing.JButton();

        ruleta.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ruleta.setText("Ruleta #3");

        ronda.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ronda.setText("Ronda #3");

        numeroSorteado.setBackground(new java.awt.Color(255, 102, 102));
        numeroSorteado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroSorteado.setText("12");

        lbl_totalApostado.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbl_totalApostado.setText("$ 153");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/money.png"))); // NOI18N

        jLbl_Apuestas_titulo.setText("Apuestas:");

        jLbl_cantidadApuestas_Valor.setText("0");

        jLabel3.setText("|");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBtn_LanzarPagar.setText("Lanzar/Pagar");
        jBtn_LanzarPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_LanzarPagarActionPerformed(evt);
            }
        });

        jBtn_CerrarMesa.setText("Cerrar mesa");
        jBtn_CerrarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CerrarMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_totalApostado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                        .addComponent(ronda)
                        .addGap(82, 82, 82)
                        .addComponent(ruleta)
                        .addGap(150, 150, 150)
                        .addComponent(jBtn_CerrarMesa)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLbl_Apuestas_titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbl_cantidadApuestas_Valor)
                        .addGap(54, 54, 54)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jBtn_LanzarPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ruleta)
                            .addComponent(ronda)
                            .addComponent(lbl_totalApostado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_CerrarMesa))
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_Apuestas_titulo)
                            .addComponent(jLbl_cantidadApuestas_Valor)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_LanzarPagar))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLbl_Apuestas_titulo.getAccessibleContext().setAccessibleName("jLbl_Apuestas_titulo");
        jLbl_cantidadApuestas_Valor.getAccessibleContext().setAccessibleName("jLbl_cantidadApuestas_Valor");
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_LanzarPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_LanzarPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_LanzarPagarActionPerformed

    private void jBtn_CerrarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CerrarMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_CerrarMesaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_CerrarMesa;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLbl_Apuestas_titulo;
    private javax.swing.JLabel jLbl_cantidadApuestas_Valor;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_totalApostado;
    private javax.swing.JLabel numeroSorteado;
    private javax.swing.JLabel ronda;
    private javax.swing.JLabel ruleta;
    // End of variables declaration//GEN-END:variables
}
