/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package componentes;

import controladores.ControladorVistaMesaCrupier;
import dominio.efectos.StrategyEfecto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JSeparator;

/**
 *
 * @author nacho
 */
public class PanelInfoCrupier extends javax.swing.JPanel {

    /**
     * Creates new form PanelInfoJugador
     */
    private List<Escuchador> escuchadores;

    public PanelInfoCrupier() {
        initComponents();
        escuchadores = new ArrayList();
    }

    public void agregar(Escuchador escuchador) {
        this.escuchadores.add(escuchador);
    }

    public void eliminarEscuchadores() {
        this.escuchadores.clear();
    }

    public void eliminarEscuchador(Escuchador escuchador) {
        this.escuchadores.remove(escuchador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void setSaldoInicial(float saldoInicial) {
        this.lbl_totalApostado.setText(String.valueOf(saldoInicial));
    }

    public void setNumeroMesa(int mesa) {
        this.ruleta.setText("Ruleta #" + String.valueOf(mesa));
    }

    public void cargarUltimoNumeroSorteado(String ultimoNumero) {
        this.jLbl_UltimoNumeroSorteado.setText(ultimoNumero); 
    }

    public void setNumeroRonda(int ronda) {
        this.ronda.setText("Ronda #" + String.valueOf(ronda));
    }

    public void setTotalApostado(int totalApostado) {
        this.lbl_totalApostado.setText(String.valueOf(totalApostado));

    }

    public void setCantidadApuestas(int cantidadApuestas) {
        this.jLbl_cantidadApuestas_Valor.setText(String.valueOf(cantidadApuestas));

    }

    public void setDropdownEfectos(String[] efectos) {
        for (String e : efectos) {
            this.cb_efectos.addItem(e);
        }

    }

    public interface Escuchador {
        public void efectoSeleccionado(String efecto);
        public void cerrarMesa();
        public void lanzarYPagar();

    }

    // Cargar listas de efectos

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ruleta = new javax.swing.JLabel();
        ronda = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLbl_UltimoNumeroSorteado = new javax.swing.JLabel();
        lbl_totalApostado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLbl_Apuestas_titulo = new javax.swing.JLabel();
        jLbl_cantidadApuestas_Valor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb_efectos = new javax.swing.JComboBox<>();
        javax.swing.JButton jBtn_LanzarPagar = new javax.swing.JButton();
        jBtn_CerrarMesa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        ruleta.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ruleta.setText("Ruleta #3");

        ronda.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ronda.setText("Ronda #3");

        jLbl_UltimoNumeroSorteado.setBackground(new java.awt.Color(255, 102, 102));
        jLbl_UltimoNumeroSorteado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_UltimoNumeroSorteado.setText("12");

        lbl_totalApostado.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbl_totalApostado.setText("$ 153");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/money.png"))); // NOI18N

        jLbl_Apuestas_titulo.setText("Apuestas:");

        jLbl_cantidadApuestas_Valor.setText("0");

        jLabel3.setText("|");

        cb_efectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_efectosActionPerformed(evt);
            }
        });

        jBtn_LanzarPagar.setText("Lanzar/Pagar");
        jBtn_LanzarPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_LanzarPagarActionPerformed(evt);
            }
        });

        jBtn_CerrarMesa.setText("Cerrar mesa");
        jBtn_CerrarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CerrarMesaActionPerformed(evt);
            }
        });

        jLabel4.setText("Ultimo Numero:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_totalApostado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                                .addComponent(ronda)
                                .addGap(82, 82, 82)
                                .addComponent(ruleta)
                                .addGap(150, 150, 150)
                                .addComponent(jBtn_CerrarMesa)
                                .addGap(98, 98, 98)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLbl_Apuestas_titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbl_cantidadApuestas_Valor)
                        .addGap(54, 54, 54)
                        .addComponent(cb_efectos, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jBtn_LanzarPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(jLbl_UltimoNumeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ruleta)
                            .addComponent(ronda)
                            .addComponent(lbl_totalApostado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_CerrarMesa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Apuestas_titulo)
                    .addComponent(jLbl_cantidadApuestas_Valor)
                    .addComponent(jLabel3)
                    .addComponent(cb_efectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_LanzarPagar)
                    .addComponent(jLbl_UltimoNumeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLbl_Apuestas_titulo.getAccessibleContext().setAccessibleName("jLbl_Apuestas_titulo");
        jLbl_cantidadApuestas_Valor.getAccessibleContext().setAccessibleName("jLbl_cantidadApuestas_Valor");
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_LanzarPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_LanzarPagarActionPerformed
        // TODO add your handling code here:
        for(Escuchador e:escuchadores){
            e.lanzarYPagar();
        }
    }//GEN-LAST:event_jBtn_LanzarPagarActionPerformed

    private void jBtn_CerrarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CerrarMesaActionPerformed
        // TODO add your handling code here:
         for (Escuchador e : escuchadores) {
            e.cerrarMesa();
        }
    }//GEN-LAST:event_jBtn_CerrarMesaActionPerformed

    private void cb_efectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_efectosActionPerformed
        // TODO add your handling code here:
        // Si la ronda esta bloqueada deshabilitar esta op[cion
        String efecto = this.cb_efectos.getSelectedItem().toString();
        for (Escuchador e : escuchadores) {
            e.efectoSeleccionado(efecto);
        }


    }//GEN-LAST:event_cb_efectosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_efectos;
    private javax.swing.JButton jBtn_CerrarMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLbl_Apuestas_titulo;
    private javax.swing.JLabel jLbl_UltimoNumeroSorteado;
    private javax.swing.JLabel jLbl_cantidadApuestas_Valor;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_totalApostado;
    private javax.swing.JLabel ronda;
    private javax.swing.JLabel ruleta;
    // End of variables declaration//GEN-END:variables
}
