/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package componentes;

import javax.swing.JLabel;
import javax.swing.JSeparator;

/**
 *
 * @author nacho
 */
public class PanelInfoJugador extends javax.swing.JPanel {
    /**
     * Creates new form PanelInfoJugador
     */
    public PanelInfoJugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void setSaldoInicial (float saldoInicial) {
        this.saldoInicial.setText("$" + String.valueOf(saldoInicial));
    }
    
    public void setNombreJugador (String nombre) {
        this.playerName.setText(nombre);
    }
    
    public void setNumeroMesa (int mesa) {
        this.ruleta.setText("Ruleta #" + String.valueOf(mesa));
    }
    
    public void setNumeroRonda (int ronda) {
        this.ronda.setText("Ronda #" + String.valueOf(ronda));
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ruleta = new javax.swing.JLabel();
        ronda = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        playerName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        numeroSorteado = new javax.swing.JLabel();
        saldoInicial = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        chip1 = new javax.swing.JButton();
        chip5 = new javax.swing.JButton();
        chip50 = new javax.swing.JButton();
        chip10 = new javax.swing.JButton();
        chip100 = new javax.swing.JButton();

        ruleta.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ruleta.setText("Ruleta #3");

        ronda.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ronda.setText("Ronda #3");

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/profile-user.png"))); // NOI18N

        playerName.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        playerName.setText("Montgomery Burns");

        numeroSorteado.setBackground(new java.awt.Color(255, 102, 102));
        numeroSorteado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroSorteado.setText("12");

        saldoInicial.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        saldoInicial.setText("$ 153");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/money.png"))); // NOI18N

        chip1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        chip1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/chip.png"))); // NOI18N
        chip1.setText("1");
        chip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chip1ActionPerformed(evt);
            }
        });

        chip5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        chip5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/chip.png"))); // NOI18N
        chip5.setText("5");

        chip50.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        chip50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/chip.png"))); // NOI18N
        chip50.setText("50");

        chip10.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        chip10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/chip.png"))); // NOI18N
        chip10.setText("10");

        chip100.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        chip100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/chip.png"))); // NOI18N
        chip100.setText("100");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saldoInicial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ruleta)
                                .addGap(18, 18, 18)
                                .addComponent(ronda)
                                .addGap(148, 148, 148)
                                .addComponent(playerName)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 157, Short.MAX_VALUE)
                                .addComponent(chip1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(chip5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(chip10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(chip50, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(chip100)
                                .addGap(104, 104, 104)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userIcon)
                            .addComponent(numeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userIcon)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ruleta)
                                .addComponent(ronda)
                                .addComponent(saldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(playerName)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chip1)
                    .addComponent(chip5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chip10)
                        .addComponent(chip50)
                        .addComponent(chip100)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chip1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chip1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chip1;
    private javax.swing.JButton chip10;
    private javax.swing.JButton chip100;
    private javax.swing.JButton chip5;
    private javax.swing.JButton chip50;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel numeroSorteado;
    private javax.swing.JLabel playerName;
    private javax.swing.JLabel ronda;
    private javax.swing.JLabel ruleta;
    private javax.swing.JLabel saldoInicial;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
