/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package componentes;

import Exceptions.NoTieneSaldoDisponibleException;
import controladores.ControladorInfoJugador;
import dominio.modelosVista.ModeloMesaJugador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import vistas.IPanelInfoJugador;

/**
 *
 * @author nacho
 */
public class PanelInfoJugador extends javax.swing.JPanel implements IPanelInfoJugador{
    
    private final ControladorInfoJugador controlador;
    private ModeloMesaJugador modelo;
    private ArrayList<Escuchador> escuchadores;
    /**
     * Creates new form PanelInfoJugador
     */
    public PanelInfoJugador() {
        initComponents();
        this.controlador = new ControladorInfoJugador ();
        this.escuchadores = new ArrayList <> ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ruleta = new javax.swing.JLabel();
        ronda = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        playerName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ultimoSorteado = new javax.swing.JLabel();
        saldoInicial = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        chip1 = new javax.swing.JButton();
        chip5 = new javax.swing.JButton();
        chip10 = new javax.swing.JButton();
        chip50 = new javax.swing.JButton();
        chip100 = new javax.swing.JButton();
        montoApostado = new javax.swing.JLabel();
        undoButton = new javax.swing.JButton();

        ruleta.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ruleta.setText("Ruleta #3");

        ronda.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ronda.setText("Ronda #3");

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/profile-user.png"))); // NOI18N

        playerName.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        playerName.setText("Montgomery Burns");

        ultimoSorteado.setBackground(new java.awt.Color(255, 102, 102));
        ultimoSorteado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ultimoSorteado.setText("12");

        saldoInicial.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        saldoInicial.setText("$ 153");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/money.png"))); // NOI18N

        chip1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/chip.png"))); // NOI18N
        chip1.setText("1");
        chip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chip1ActionPerformed(evt);
            }
        });

        chip5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/chip.png"))); // NOI18N
        chip5.setText("5");
        chip5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chip5ActionPerformed(evt);
            }
        });

        chip10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/chip.png"))); // NOI18N
        chip10.setText("10");
        chip10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chip10ActionPerformed(evt);
            }
        });

        chip50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/chip.png"))); // NOI18N
        chip50.setText("50");
        chip50.setToolTipText("");
        chip50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chip50ActionPerformed(evt);
            }
        });

        chip100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/chip.png"))); // NOI18N
        chip100.setText("100");
        chip100.setToolTipText("");
        chip100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chip100ActionPerformed(evt);
            }
        });

        montoApostado.setText("MontoApostado");

        undoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/arrows.png"))); // NOI18N
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saldoInicial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ruleta)
                        .addGap(18, 18, 18)
                        .addComponent(ronda)
                        .addGap(124, 124, 124)
                        .addComponent(playerName)
                        .addGap(57, 57, 57)
                        .addComponent(userIcon))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(montoApostado)
                        .addGap(55, 55, 55)
                        .addComponent(chip1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(chip5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(chip10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(chip50, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(chip100)
                        .addGap(18, 18, 18)
                        .addComponent(undoButton)
                        .addGap(18, 18, 18)
                        .addComponent(ultimoSorteado, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ruleta)
                                .addComponent(ronda)
                                .addComponent(saldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(playerName)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chip1)
                        .addComponent(chip5)
                        .addComponent(chip10)
                        .addComponent(chip50)
                        .addComponent(chip100)
                        .addComponent(montoApostado))
                    .addComponent(undoButton)
                    .addComponent(ultimoSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chip1ActionPerformed
        this.tomarFicha(1);
        this.triggerEventSelectedChip(1);
    }//GEN-LAST:event_chip1ActionPerformed

    private void chip5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chip5ActionPerformed
        this.tomarFicha(5);
        this.triggerEventSelectedChip(5);
    }//GEN-LAST:event_chip5ActionPerformed

    private void chip10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chip10ActionPerformed
        this.tomarFicha(10);
        this.triggerEventSelectedChip(10);
    }//GEN-LAST:event_chip10ActionPerformed

    private void chip50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chip50ActionPerformed
        this.tomarFicha(50);
        this.triggerEventSelectedChip(50);
    }//GEN-LAST:event_chip50ActionPerformed

    private void chip100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chip100ActionPerformed
        this.tomarFicha(100);
        this.triggerEventSelectedChip(100);
    }//GEN-LAST:event_chip100ActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        this.undo();
    }//GEN-LAST:event_undoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chip1;
    private javax.swing.JButton chip10;
    private javax.swing.JButton chip100;
    private javax.swing.JButton chip5;
    private javax.swing.JButton chip50;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel montoApostado;
    private javax.swing.JLabel playerName;
    private javax.swing.JLabel ronda;
    private javax.swing.JLabel ruleta;
    private javax.swing.JLabel saldoInicial;
    private javax.swing.JLabel ultimoSorteado;
    private javax.swing.JButton undoButton;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
    
    private void undo () {
        this.controlador.undo (this.modelo);
        this.actualizar ();
    }
    
    private void tomarFicha(int i) {
        try {
            this.controlador.tomarFicha (i, this.modelo, this);
            int monto = 1 + this.modelo.getTotal();
            this.modelo.agregarFicha (i);
            this.actualizar();
        } catch (NoTieneSaldoDisponibleException ex) {
            this.mostrarDialogoDeError(ex.getMessage());
        }
    }
    
    public void actualizar () {
        this.setNombreJugador();
        this.setSaldoInicial();
        this.setNumeroMesa();
        this.setNumeroRonda();
        this.setMontoApostado();
        this.setUltimoSorteado();
    }

    @Override
    public void mostrarDialogoDeError(String message) {
        JOptionPane.showMessageDialog(this, message, "Saldo insuficiente", JOptionPane.ERROR_MESSAGE);
    }
    
    public void setSaldoInicial () {
        this.saldoInicial.setText("$" + String.valueOf(this.modelo.getSaldoJugador()));
    }
    
    public void setNombreJugador () {
        this.playerName.setText(this.modelo.getNombreJugador());
    }
    
    public void setNumeroMesa () {
        this.ruleta.setText("Ruleta #" + String.valueOf(this.modelo.getMesa()));
    }
    
    public void setNumeroRonda () {
        this.ronda.setText("Ronda #" + String.valueOf(this.modelo.getRonda()));
    }
    
    public void setMontoApostado () {
        this.montoApostado.setText("Apuesta: $" + String.valueOf(this.modelo.getTotal()));
    }
    
    public void setUltimoSorteado () {
        this.ultimoSorteado.setText (modelo.getUltimoSorteado());
    }
         
     public ModeloMesaJugador getModelo() {
        return modelo;
    }

    public void setModelo(ModeloMesaJugador modelo) {
        this.modelo = modelo;
    }
    
    public void addEventListener (Escuchador listener) {
        this.escuchadores.add(listener);
    }
    
    public void removeEventLitener (Escuchador listener) {
        this.escuchadores.remove(listener);
    }
    
    public void triggerEventSelectedChip (int chip) {
        this.escuchadores.forEach(listener -> listener.fichaSeleccionada(chip));
    }
    
    public interface Escuchador {
        public void fichaSeleccionada (int ficha);
    }
    
}
